name: Tests

on:
  pull_request:
  push:

jobs:
  x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          python-version: 3.8

    steps:
    - name: Checkout pygit2
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt install tinyproxy
        LIBSSH2_VERSION=1.10.0 LIBGIT2_VERSION=1.3.0 /bin/sh build.sh test
        pytest


  aarch64:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout pygit2
      uses: actions/checkout@v2
    - name: Build & test
      uses: uraimo/run-on-arch-action@v2.1.1
      with:
        arch: aarch64
        distro: ubuntu20.04
        install: |
          apt-get update -q -y
          apt-get install -q -y cmake libssl-dev python3-dev python3-venv wget
        run: |
          LIBSSH2_VERSION=1.10.0 LIBGIT2_VERSION=1.3.0 /bin/sh build.sh test
          pytest
